### PR TITLE
Improve livenessProbe and readinessProbe configs

### PR DESCRIPTION
**Pull request by dfoxg**
**Description of the change**

Improve the liveness and readiness probes, since my container was regulary killed due a timeout of the liveness probe script:
```
-> kubectl get pods -A
uptime-kuma     uptime-kuma-helm-8568db8bfd-7w6xl              1/1     Running     174 (12h ago)   30d
```

```
-> kubectl get events
2m27s       Normal    Created             pod/uptime-kuma-helm-57f9d6fd5c-czdlh    Created container uptime-kuma
2m27s       Normal    Started             pod/uptime-kuma-helm-57f9d6fd5c-czdlh    Started container uptime-kuma
2m23s       Warning   Unhealthy           pod/uptime-kuma-helm-57f9d6fd5c-czdlh    Readiness probe failed: Get "http://10.42.0.186:3001/": dial tcp 10.42.0.186:3001: connect: connection refused
2m22s       Warning   Unhealthy           pod/uptime-kuma-helm-57f9d6fd5c-czdlh    Liveness probe failed: Health Check ERROR
2s          Warning   Unhealthy           pod/uptime-kuma-helm-57f9d6fd5c-czdlh    Liveness probe failed: command "node extra/healthcheck.js" timed out
```

### CODE REVIEW

**Comment by dirsigler** [comment]
Hey @dfoxg 
sorry that it killed your deployment previously.

If you don't mind I would suggest that we add these changes as Helm programmable values.
Furthermore I would appreciate if we can add the timeouts also to the [Statefulset](https://github.com/dirsigler/uptime-kuma-helm/blob/main/charts/uptime-kuma/templates/statefulset.yaml).

Thank you!

**Comment by dfoxg** [comment]
@dirsigler thanks for your quick reply. I´ve updated the PR :)

**Review by dirsigler — APPROVED** [review]
/lgtm

**Comment by dirsigler** [comment]
Thank you very much for this contribution :)

**Pull request merged**
