### PR TITLE
Some minor changes for newer cluster versions and support for storageClassName

### PR DESCRIPTION
**Pull request by malagant**
As promised in https://github.com/louislam/uptime-kuma/issues/763 I tried the chart and added some small tweaks that I needed and I think this is helpful for others as well.

### CODE REVIEW

**Comment by dirsigler** [comment]
Thank you very much! Was already sitting on the Ingress update myself but really appreciate that you were faster than me :D

**Comment by dirsigler** [comment]
@malagant seems like it also needs a version bump.
Could you please bump the Chart Version for one Minor Patch to 0.4.6 ?
https://github.com/dirsigler/uptime-kuma-helm/blob/main/charts/uptime-kuma/Chart.yaml#L14

**Comment by malagant** [comment]
Sorry, I always forget to bump versions. ˆˆ

**Comment by malagant** [comment]
Now let me fix the linting error

**Comment by dirsigler** [comment]
closed due to some major changes on the code.
But still thank you very much for this contribution!

**Pull request closed without merging**
